#tomcat port
server:
  port: 9003
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee?serverTimezone=Asia/Seoul
    username: snow
    password: 561378
#mybatis
mybatis:
  type-aliases-package: data.model.*    #dao등록 dto등록
  mapper-locations:
  - /mapper/**/*.xml
